services:
  - type: web
    name: chainpilot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NETWORK_RPC_URL
        value: https://mainnet.base.org
      - key: NETWORK_CHAIN_ID
        value: 8453
      - key: WALLET_ADDRESS
        value: 0xab4862f2d4a158F2460f30126a697C4180933924
      - key: CONTRACT_EXECUTOR_ADDRESS
        value: 0x3175F8bDBEE3FaE7e3369eB352BADcd4237161AC
      - key: CONTRACT_SCHEDULER_ADDRESS
        value: 0x1dc4052FDEc1CC197a280B19a657704bc1910BBf
      - key: CONTRACT_TOKEN_ADDRESS
        value: 0x_MAINNET_TOKEN_ADDRESS_
    # Add WALLET_PRIVATE_KEY as a secret in Render dashboard