services:
  - type: web
    name: chainpilot
    env: python
    plan: free
    repo: https://github.com/Siphocha/ChainPilot
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: NETWORK_RPC_URL
        value: https://mainnet.base.org
      - key: NETWORK_CHAIN_ID
        value: 8453
      - key: WALLET_ADDRESS
        value: 0xab4862f2d4a158F2460f30126a697C4180933924
      - key: CONTRACT_EXECUTOR_ADDRESS
        value: 0x3175F8bDBEE3FaE7e3369eB352BADcd4237161AC
      - key: CONTRACT_SCHEDULER_ADDRESS
        value: 0x1dc4052FDEc1CC197a280B19a657704bc1910BBf
      - key: PYTHONUNBUFFERED
        value: 1
      - key: WALLET_PRIVATE_KEY
        fromService:
          type: secret
          name: WALLET_PRIVATE_KEY