services:
  - type: web
    name: chainpilot
    env: docker
    plan: free
    repo: https://github.com/Siphocha/ChainPilot
    autoDeploy: true
    dockerfilePath: Dockerfile
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: NETWORK_RPC_URL
        value: https://base-mainnet.g.alchemy.com/v2/YSXzyJPDegocuyAhlTwa8u4NSjJHFfP2
      - key: NETWORK_CHAIN_ID
        value: 8453
      - key: WALLET_ADDRESS
        value: 0xab4862f2d4a158F2460f30126a697C4180933924
      - key: CONTRACT_EXECUTOR_ADDRESS
        value: 0x3175F8bDBEE3FaE7e3369eB352BADcd4237161AC
      - key: CONTRACT_SCHEDULER_ADDRESS
        value: 0x1dc4052FDEc1CC197a280B19a657704bc1910BBf
      - key: PYTHONUNBUFFERED
        value: 1
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: CDP_API_KEY_NAME
        value: TestKey
      - key: BASESCAN_API_KEY
        value: UW519K6C66F6E4YTZHVRD87X29BG9U3ZQ3
      - key: FRONTEND_URL
        value: https://chain-pilot-drab.vercel.app