/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutomationAgent } from "./IAutomationAgent";
export type { IExecutor } from "./IExecutor";
export type { IScheduler } from "./IScheduler";
export type { ITemplateManager } from "./ITemplateManager";
