/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as executorSol from "./Executor.sol";
export type { executorSol };
import type * as schedulerSol from "./Scheduler.sol";
export type { schedulerSol };
export type { AutomationAgent } from "./AutomationAgent";
export type { TemplateManager } from "./TemplateManager";
