/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ChainPilotExecutor: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes",
              name: "reason",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ExpiredApproval",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "actual",
              type: "uint256",
            },
          ],
          name: "InvalidValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
          ],
          name: "UnauthorizedExecuter",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "TaskApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "approveTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
          ],
          name: "getTaskHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "userApprovals",
          outputs: [
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    ChainPilotScheduler: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_executer",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "reason",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "executeAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiry",
              type: "uint256",
            },
          ],
          name: "ExecutionWindowExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "executeAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "currentTime",
              type: "uint256",
            },
          ],
          name: "ExecutionWindowNotReached",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ExpiredApproval",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "InvalidTask",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "from",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "to",
              type: "uint256",
            },
          ],
          name: "InvalidTimeWindow",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "actual",
              type: "uint256",
            },
          ],
          name: "InvalidValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskAlreadyCancelled",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "Unauthorized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
          ],
          name: "UnauthorizedExecuter",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "TaskApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "executor",
              type: "address",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "executer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "TaskScheduled",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "approveTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "cancelTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "executerAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "from",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "to",
              type: "uint256",
            },
          ],
          name: "getPendingTasks",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
          ],
          name: "getTaskHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "scheduleTask",
          outputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "taskIdCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "tasks",
          outputs: [
            {
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "executer",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isCancelled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "userApprovals",
          outputs: [
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  84532: {
    ChainPilotExecutor: {
      address: "0x4dbe111826890E2E84499148511440e19e1C4A8D",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes",
              name: "reason",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ExpiredApproval",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "actual",
              type: "uint256",
            },
          ],
          name: "InvalidValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
          ],
          name: "UnauthorizedExecuter",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "TaskApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "approveTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
          ],
          name: "getTaskHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "userApprovals",
          outputs: [
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    ChainPilotScheduler: {
      address: "0x97a34FdA6569a5FD3020720aA4eF20E1E75b1CA8",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_executer",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "reason",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "executeAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiry",
              type: "uint256",
            },
          ],
          name: "ExecutionWindowExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "executeAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "currentTime",
              type: "uint256",
            },
          ],
          name: "ExecutionWindowNotReached",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ExpiredApproval",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "InvalidTask",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "from",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "to",
              type: "uint256",
            },
          ],
          name: "InvalidTimeWindow",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "actual",
              type: "uint256",
            },
          ],
          name: "InvalidValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskAlreadyCancelled",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "Unauthorized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
          ],
          name: "UnauthorizedExecuter",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "TaskApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "TaskCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "taskHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "executor",
              type: "address",
            },
          ],
          name: "TaskExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "executer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "TaskScheduled",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "approveTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "cancelTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "executeTask",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "executerAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "from",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "to",
              type: "uint256",
            },
          ],
          name: "getPendingTasks",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
          ],
          name: "getTaskHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "payload",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "scheduleTask",
          outputs: [
            {
              internalType: "uint256",
              name: "taskId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "taskIdCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "tasks",
          outputs: [
            {
              internalType: "uint64",
              name: "executeAt",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "expiryAt",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "address",
              name: "executer",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isCancelled",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "userApprovals",
          outputs: [
            {
              internalType: "uint256",
              name: "maxValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
