/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface _SchedulerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTask"
      | "getPendingTasks"
      | "scheduleTask"
      | "taskIdCounter"
      | "tasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TaskCancelled" | "TaskScheduled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingTasks",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleTask",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskScheduledEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    user: AddressLike,
    executeAt: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, user: string, executeAt: bigint];
  export interface OutputObject {
    taskId: bigint;
    user: string;
    executeAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface _Scheduler extends BaseContract {
  connect(runner?: ContractRunner | null): _Scheduler;
  waitForDeployment(): Promise<this>;

  interface: _SchedulerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  getPendingTasks: TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [bigint[]],
    "view"
  >;

  scheduleTask: TypedContractMethod<
    [executeAt: BigNumberish, target: AddressLike, payload: BytesLike],
    [bigint],
    "nonpayable"
  >;

  taskIdCounter: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        executeAt: bigint;
        user: string;
        target: string;
        payload: string;
        isCancelled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPendingTasks"
  ): TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "scheduleTask"
  ): TypedContractMethod<
    [executeAt: BigNumberish, target: AddressLike, payload: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        executeAt: bigint;
        user: string;
        target: string;
        payload: string;
        isCancelled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskScheduled"
  ): TypedContractEvent<
    TaskScheduledEvent.InputTuple,
    TaskScheduledEvent.OutputTuple,
    TaskScheduledEvent.OutputObject
  >;

  filters: {
    "TaskCancelled(uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskScheduled(uint256,address,uint256)": TypedContractEvent<
      TaskScheduledEvent.InputTuple,
      TaskScheduledEvent.OutputTuple,
      TaskScheduledEvent.OutputObject
    >;
    TaskScheduled: TypedContractEvent<
      TaskScheduledEvent.InputTuple,
      TaskScheduledEvent.OutputTuple,
      TaskScheduledEvent.OutputObject
    >;
  };
}
