/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAutomationAgent,
  IAutomationAgentInterface,
} from "../../../contracts/interfaces/IAutomationAgent";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
    ],
    name: "executeTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAutomationAgent__factory {
  static readonly abi = _abi;
  static createInterface(): IAutomationAgentInterface {
    return new Interface(_abi) as IAutomationAgentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAutomationAgent {
    return new Contract(address, _abi, runner) as unknown as IAutomationAgent;
  }
}
