/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExecutor,
  IExecutorInterface,
} from "../../../contracts/interfaces/IExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
    ],
    name: "executeTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IExecutorInterface {
    return new Interface(_abi) as IExecutorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IExecutor {
    return new Contract(address, _abi, runner) as unknown as IExecutor;
  }
}
