/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IScheduler,
  ISchedulerInterface,
} from "../../../contracts/interfaces/IScheduler";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
    ],
    name: "cancelTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "executeAt",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "scheduleTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IScheduler__factory {
  static readonly abi = _abi;
  static createInterface(): ISchedulerInterface {
    return new Interface(_abi) as ISchedulerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IScheduler {
    return new Contract(address, _abi, runner) as unknown as IScheduler;
  }
}
