/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITemplateManager,
  ITemplateManagerInterface,
} from "../../../contracts/interfaces/ITemplateManager";

const _abi = [
  {
    inputs: [],
    name: "deployTemplate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITemplateManager__factory {
  static readonly abi = _abi;
  static createInterface(): ITemplateManagerInterface {
    return new Interface(_abi) as ITemplateManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITemplateManager {
    return new Contract(address, _abi, runner) as unknown as ITemplateManager;
  }
}
