name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: AI Agent/ChainPilot/yarn.lock
      - name: Install Dependencies
        working-directory: AI Agent/ChainPilot
        run: yarn install
      - name: Build
        working-directory: AI Agent/ChainPilot
        run: yarn build