name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure submodules are checked out
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        working-directory: AI Agent/ChainPilot # Run in the submodule directory
        run: yarn install
      - name: Build
        working-directory: AI Agent/ChainPilot
        run: yarn build